### ISSUE TITLE
manage_repos should not be on by default on all distros

### ISSUE THREAD

**Issue by tampakrap** [puppetlabs-operations/puppet-puppet#170]
$puppet::agent::manage_repos currently is on for all distros by default. Since there are no puppetlabs provided repos for many of the supported distros, I would like to propose either of the followings:

1) Leave it on only for Debian/Ubuntu and Centos/Fedora/Red Hat
2) Default it to off

Let me know if any of the above solutions is acceptable and I'll work on the PR

**Comment by igalic** [comment]
i have a strong preference for 2), because i like to manage all repositories on **one** place, rather than ***all over the place***

**Comment by tampakrap** [comment]
https://github.com/puppetlabs-operations/puppet-puppet/pull/172
