### ISSUE TITLE
request for 0.13.1

### ISSUE THREAD

**Issue by tampakrap** [puppetlabs-operations/puppet-puppet#179]
The bug that e32f84986aa42fd36feb6cd0e5d13939052d077d is solving is quite important to me, thus I hereby request a new patch release 0.13.1 of this module

**Comment by danieldreier** [comment]
I pushed the v0.13.1 tag to the forge. It doesn't have more recent commits but should cover the one you were looking for. I'd strongly encourage you to use r10k to deploy directly from github because then you can use whatever git commit hash you want rather than waiting for forge releases.

**Comment by tampakrap** [comment]
Thanks, I am already doing it that way but I prefer forge modules for various reasons
