### ISSUE TITLE
our default `default_manifest` of `undef` breaks puppet runs

### ISSUE THREAD

**Issue by igalic** [puppetlabs-operations/puppet-puppet#191]
… or makes them really faster, depending on your pov…
it returns an empty catalogue (especially in directory environments) which we've switched on by default.

so, our defaults don't really match up.

**Comment by igalic** [comment]
see also: [PUP-4053](https://tickets.puppetlabs.com/browse/PUP-4053)

**Comment by tampakrap** [comment]
fixed in #207
