### ISSUE TITLE
release 1.0.0

### ISSUE THREAD

**Issue by igalic** [puppetlabs-operations/puppet-puppet#214]
i think we should make a release of 1.0.0

then we can branch off 2.0.x and start whacking away at #205 and #116.

**Comment by tampakrap** [comment]
I'm fine with either 1.0.0 or 0.2.0, but I would really like to follow semver and write decent changelog entries from now on

**Comment by igalic** [comment]
i suggest we follow semver, and go for 1.0.0.
see also, @boennemann's http://hauptversionsnummernerhoehungs.angst.software / [jsconf bp talk (once it's released)](http://jsconfbp.com/#boennemann)

i really wish we had something like that for puppet… blacksmith is not enough ;)

as for #205, we could (re-)use [puppetlabs-agent_upgrade](https://github.com/puppetlabs/puppetlabs-agent_upgrade), and then, following the example of [puppet-stash](https://github.com/puppet-community/puppet-stash) et-al, set a version fact, so we know it's updated, and doesn't need another execution of that module…

**Comment by xaque208** [comment]
I've added https://github.com/puppetlabs-operations/puppet-puppet/milestones/1.0.0  Is there anything else we should include for that release?

**Comment by igalic** [comment]
LGTM

**Comment by tampakrap** [comment]
I disagree about the gentoo issue, the rest are fine. I also added my open PRs

**Comment by danieldreier** [comment]
@tampakrap thanks for making a bunch of PRs to help move this forward -- sorry it's taken so long to get them merged/reviewed.

**Comment by mvisonneau** [comment]
Is there any plan about going forward with this ?

**Comment by tampakrap** [comment]
@danieldreier any chance we can have a 1.0.0 release now? The remaining issues can be worked on later imho

**Comment by danieldreier** [comment]
I'm fine with this. I'll cut a 1.0.0 release later today.

**Comment by danieldreier** [comment]
Okay. I've made a 1.0.0 release, published it as a release here, and pushed it to the forge. Please re-open this if I missed something.
